import React,{useEffect,useState}from'react';
import{LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,AreaChart,Area}from'recharts';
const Gauge=({value,max,unit,label,available=true})=>{if(!available)return <div className="gauge unavailable"><div className="ring"><div className="ring-inner"><b>--</b><span>{unit}</span></div></div><div className="gauge-label">NO DATA</div><div className="meter"><i style={{width:'0%'}}/></div></div>;const n=Number(value),p=Math.min(100,Math.max(0,n/max*100));return <div className="gauge"><div className="ring" style={{'--p':p+'%'}}><div className="ring-inner"><b>{n}</b><span>{unit}</span></div></div><div className="gauge-label">{label}</div><div className="meter"><i style={{width:p+'%'}}/></div></div>};
const Card=({title,icon,children,extra=''})=><section className="card"><div className="card-head"><span>{icon} {title}</span><small>{extra}</small></div>{children}</section>;
const now=()=>new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'});
const isFresh=t=>!!t&&(Date.now()-new Date(t).getTime()<10000);
export default function App(){
 const[latest,setLatest]=useState({temperature:null,humidity:null,mq3:null,mq7:null,pir:null,ir:null,buzzer:null,fan:null,updatedAt:null,lastDeviceUpdate:null});
 const[data,setData]=useState([]),[connected,setConnected]=useState(false),[hasData,setHasData]=useState(false);
 const[alerts,setAlerts]=useState([{time:now(),text:'Waiting for ESP8266 connection',type:'NORMAL'}]);
 const[autoFan,setAutoFan]=useState(true),[threshold,setThreshold]=useState(35);
 const addAlert=(text,type='WARNING')=>setAlerts(a=>[{time:now(),text,type},...a].slice(0,12));
 const poll=async()=>{try{const r=await fetch('/api/status',{cache:'no-store'});if(!r.ok)throw 0;const s=await r.json();const fresh=isFresh(s.lastDeviceUpdate);setConnected(fresh);setHasData(fresh||!!s.lastDeviceUpdate);setLatest(s);if(fresh&&s.temperature!=null)setData(d=>[...d.slice(-19),{t:now(),temp:Number(s.temperature),hum:Number(s.humidity)}]);}catch{setConnected(false)}};
 useEffect(()=>{poll();const id=setInterval(poll,2000);return()=>clearInterval(id)},[]);
 const available=connected&&hasData, high=available&&Number(latest.temperature)>=threshold,gas=available&&Number(latest.mq3)>=50,co=available&&Number(latest.mq7)>=50;
 const critical=gas||co,warning=high||latest.pir===true||latest.ir===true,status=!available?'OFFLINE':critical?'CRITICAL':warning?'WARNING':'SAFE';
 const test=async(field,label)=>{try{await fetch('/api/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({[field]:!latest[field],source:'dashboard-test'})});await poll();addAlert(label)}catch{addAlert('API unavailable','CRITICAL')}};
 const fan=async value=>{try{await fetch('/api/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fan:value,source:'dashboard-command'})});await poll()}catch{addAlert('Fan command failed','CRITICAL')}};
 useEffect(()=>{if(latest.pir===true&&connected)addAlert('PIR motion detected')},[latest.pir,connected]);
 useEffect(()=>{if(latest.ir===true&&connected)addAlert('IR object detected')},[latest.ir,connected]);
 useEffect(()=>{if(gas)addAlert('MQ-3 gas/alcohol level high','CRITICAL')},[gas]);
 useEffect(()=>{if(co)addAlert('MQ-7 CO level high','CRITICAL')},[co]);
 const display=v=>v==null?'--':v;
 return <div className="app"><header><div className="brand"><span className="shield">⬡</span><div><h1>SMART CABIN SAFETY</h1><p>Vehicle safety monitoring & automation</p></div></div><div className="connection"><span className={'dot '+(connected?'online':'')}/><div><b>{connected?'ESP8266 ONLINE':'ESP8266 OFFLINE'}</b><small>{connected?'Live device • heartbeat OK':hasData?'Last known data • device offline':'No device data received'}</small></div></div></header>
 <main><div className={'status card '+(!available?'offline':'')}><div><span className="eyebrow">LIVE SYSTEM STATUS</span><h2 className={status.toLowerCase()}>{status}</h2><p>{!available?'Connect the NodeMCU to show live sensor data':critical?'Immediate attention required':warning?'Safety condition detected':'All monitored conditions are normal'}</p>{hasData&&!connected&&<div className="last-known">LAST KNOWN DATA • {latest.lastDeviceUpdate?new Date(latest.lastDeviceUpdate).toLocaleTimeString():''}</div>}</div><div className="status-orb">{!available?'—':critical?'⚠':warning?'!':'✓'}</div><div className="status-stats"><span><b>{display(latest.temperature)}{available?'°C':''}</b> Temperature</span><span><b>{display(latest.humidity)}{available?'%':''}</b> Humidity</span><span><b>{available?(latest.fan?'ON':'OFF'):'--'}</b> Fan</span></div></div>
 <div className="grid gauges"><Card title="Temperature" icon="🌡"><Gauge value={latest.temperature} max={50} unit="°C" label={high?'HIGH':'NORMAL'} available={available}/></Card><Card title="Humidity" icon="💧"><Gauge value={latest.humidity} max={100} unit="%" label="RELATIVE HUMIDITY" available={available}/></Card><Card title="MQ-3 Gas / Alcohol" icon="🧪"><Gauge value={latest.mq3} max={100} unit="%" label={gas?'DETECTED':'NORMAL'} available={available}/>{available&&<button className={gas?'danger':''} onClick={()=>test('mq3',gas?'MQ-3 test cleared':'MQ-3 test alert')}>{gas?'Clear test':'Test alert'}</button>}</Card><Card title="MQ-7 Carbon Monoxide" icon="☁"><Gauge value={latest.mq7} max={100} unit="%" label={co?'DETECTED':'NORMAL'} available={available}/>{available&&<button className={co?'danger':''} onClick={()=>test('mq7',co?'MQ-7 test cleared':'MQ-7 test alert')}>{co?'Clear test':'Test alert'}</button>}</Card></div>
 <div className="grid lower"><Card title="Cabin Sensors" icon="◉" extra={available?'LIVE':'NO DATA'}><div className="rows"><div><span>👤 PIR Motion</span><b className={!available?'muted':latest.pir?'warn':'ok'}>{!available?'NO DATA':latest.pir?'MOTION':'CLEAR'}</b>{available&&<button onClick={()=>test('pir','PIR test toggled')}>Test</button>}</div><div><span>◈ IR Object Detection</span><b className={!available?'muted':latest.ir?'warn':'ok'}>{!available?'NO DATA':latest.ir?'OBJECT':'CLEAR'}</b>{available&&<button onClick={()=>test('ir','IR test toggled')}>Test</button>}</div><div><span>🧪 MQ-3</span><b className={!available?'muted':gas?'bad':'ok'}>{!available?'NO DATA':gas?'ALERT':'NORMAL'}</b></div><div><span>☁ MQ-7</span><b className={!available?'muted':co?'bad':'ok'}>{!available?'NO DATA':co?'ALERT':'NORMAL'}</b></div></div></Card>
 <Card title="Actuators & Automation" icon="⚙"><div className="rows"><div><span>🔊 Buzzer Alert</span><b className={!available?'muted':latest.buzzer?'warn':'ok'}>{!available?'NO DATA':latest.buzzer?'ON':'OFF'}</b></div><div><span>🌀 12V Cooling Fan</span><b className={!available?'muted':latest.fan?'ok':'muted'}>{!available?'NO DATA':latest.fan?'ON':'OFF'}</b>{available&&<button onClick={()=>fan(!latest.fan)}>{latest.fan?'Turn off':'Turn on'}</button>}</div><div><span>Automatic temperature fan</span><label className="switch"><input type="checkbox" checked={autoFan} onChange={e=>setAutoFan(e.target.checked)}/><i/></label></div><div className="threshold"><span>Fan threshold</span><input type="range" min="25" max="45" value={threshold} onChange={e=>setThreshold(+e.target.value)}/><b>{threshold}°C</b></div></div></Card></div>
 <Card title="Sensor History" icon="▥" extra={connected?'LIVE':'PAUSED'}><div className="chart">{connected?<ResponsiveContainer width="100%" height={270}><AreaChart data={data}><CartesianGrid strokeDasharray="3 3" opacity=".15"/><XAxis dataKey="t"/><YAxis/><Tooltip/><Area type="monotone" dataKey="temp" strokeWidth={2} stroke="currentColor" fill="none" name="Temperature °C"/><Line type="monotone" dataKey="hum" strokeWidth={2} strokeDasharray="5 5" stroke="currentColor" name="Humidity %"/></AreaChart></ResponsiveContainer>:<div className="chart-empty">Waiting for live ESP8266 readings…</div>}</div></Card>
 <div className="grid bottom"><Card title="Alert History" icon="◷"><div className="alerts">{alerts.map((a,i)=><div className="alert" key={i}><span className={'alert-icon '+a.type.toLowerCase()}>{a.type==='NORMAL'?'✓':'!'}</span><div><b>{a.text}</b><small>{a.time}</small></div><em>{a.type}</em></div>)}</div></Card><Card title="System Information" icon="ⓘ"><div className="info"><div><span>Device</span><b>NodeMCU V3 / ESP8266</b></div><div><span>Connection</span><b className={connected?'ok':'bad'}>{connected?'Wi-Fi / API':'Offline'}</b></div><div><span>Last heartbeat</span><b>{latest.lastDeviceUpdate?new Date(latest.lastDeviceUpdate).toLocaleTimeString():'--'}</b></div><div><span>Fan logic</span><b>{autoFan?'Automatic':'Manual'}</b></div><div><span>Data source</span><b>{connected?'ESP8266':'No live device'}</b></div></div></Card></div></main><footer>SMART CABIN SAFETY • ESP8266 IoT Monitoring Platform</footer></div>}