import React,{useEffect,useState}from'react';
import{LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,AreaChart,Area}from'recharts';
const now=()=>new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'}),fresh=t=>!!t&&(Date.now()-new Date(t).getTime()<10000);
const Card=({title,icon,children,extra=''})=><section className="card"><div className="card-head"><span>{icon} {title}</span><small>{extra}</small></div>{children}</section>;
const Gauge=({value,max,unit,label,available})=>{if(!available)return <div className="gauge unavailable"><div className="ring"><div className="ring-inner"><b>--</b><span>{unit}</span></div></div><div className="gauge-label">NO DATA</div><div className="meter"><i style={{width:'0%'}}/></div></div>;const n=Number(value),p=Math.min(100,Math.max(0,n/max*100));return <div className="gauge"><div className="ring" style={{'--p':p+'%'}}><div className="ring-inner"><b>{n}</b><span>{unit}</span></div></div><div className="gauge-label">{label}</div><div className="meter"><i style={{width:p+'%'}}/></div></div>};
export default function App(){
 const[latest,setLatest]=useState({temperature:null,humidity:null,mq3:null,mq7:null,pir:null,ir:null,buzzer:null,fan:null,lastDeviceUpdate:null}),[connected,setConnected]=useState(false),[history,setHistory]=useState([]),[alerts,setAlerts]=useState([]),[events,setEvents]=useState([]),[threshold,setThreshold]=useState(35),[autoFan,setAutoFan]=useState(true),[tab,setTab]=useState('overview'),[apiMs,setApiMs]=useState(null),[testing,setTesting]=useState(false);
 const addAlert=(text,type='WARNING')=>setAlerts(a=>[{time:now(),text,type},...a].slice(0,30));
 const poll=async()=>{const started=performance.now();try{const r=await fetch('/api/status',{cache:'no-store'});if(!r.ok)throw 0;const s=await r.json();setApiMs(Math.round(performance.now()-started));const on=fresh(s.lastDeviceUpdate);setConnected(on);setLatest(s);if(on&&s.temperature!=null)setHistory(h=>[...h.slice(-59),{t:now(),temp:Number(s.temperature),hum:Number(s.humidity)}]);}catch{setConnected(false)}};
 useEffect(()=>{poll();const i=setInterval(poll,2000);return()=>clearInterval(i)},[]);
 const available=connected, t=Number(latest.temperature),high=available&&t>=threshold,gas=available&&Number(latest.mq3)>=50,co=available&&Number(latest.mq7)>=50,critical=gas||co,warning=high||latest.pir===true||latest.ir===true,status=!available?'OFFLINE':critical?'CRITICAL':warning?'WARNING':'SAFE';
 const score=!available?null:Math.max(0,100-(gas?35:0)-(co?35:0)-(high?15:0)-(latest.pir?10:0)-(latest.ir?5:0));
 const test=async(field)=>{setTesting(true);try{const v=!latest[field];await fetch('/api/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({[field]:v,source:'dashboard-test'})});setEvents(e=>[{time:now(),event:'TEST '+field.toUpperCase(),value:String(v),level:v?'WARNING':'NORMAL'},...e].slice(0,30));addAlert(field.toUpperCase()+' test '+(v?'triggered':'cleared'),v?'WARNING':'NORMAL');await poll()}finally{setTesting(false)}};
 const command=async(cmd,value)=>{try{await fetch('/api/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({[cmd]:value,source:'dashboard-command'})});addAlert(cmd.toUpperCase()+' command sent','NORMAL');await poll()}catch{addAlert('Command failed','CRITICAL')}};
 const clearAlerts=()=>setAlerts([]);
 useEffect(()=>{if(available&&latest.pir)addAlert('PIR motion detected')},[latest.pir,available]);useEffect(()=>{if(available&&latest.ir)addAlert('IR object detected')},[latest.ir,available]);useEffect(()=>{if(gas)addAlert('MQ-3 gas/alcohol alert','CRITICAL')},[gas]);useEffect(()=>{if(co)addAlert('MQ-7 CO alert','CRITICAL')},[co]);
 return <div className="app"><header><div className="brand"><span className="shield">⬡</span><div><h1>SMART CABIN SAFETY</h1><p>Vehicle safety monitoring & automation</p></div></div><div className="connection"><span className={'dot '+(connected?'online':'')}/><div><b>{connected?'ESP8266 ONLINE':'ESP8266 OFFLINE'}</b><small>{connected?'Heartbeat OK • '+(apiMs??'--')+' ms API':'No live device data'}</small></div></div></header><main>
 <div className="tabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Overview</button><button className={tab==='events'?'active':''} onClick={()=>setTab('events')}>Event Log</button><button className={tab==='tests'?'active':''} onClick={()=>setTab('tests')}>Hardware Test</button></div>
 {tab==='overview'&&<><div className={'status card '+(!available?'offline':'')}><div><span className="eyebrow">LIVE SYSTEM STATUS</span><h2 className={status.toLowerCase()}>{status}</h2><p>{!available?'Connect NodeMCU V3 to start live monitoring':critical?'Immediate attention required':warning?'Safety condition detected':'All monitored conditions are normal'}</p>{latest.lastDeviceUpdate&&!available&&<div className="last-known">LAST KNOWN DATA • {new Date(latest.lastDeviceUpdate).toLocaleTimeString()}</div>}</div><div className="status-orb">{!available?'—':critical?'⚠':warning?'!':'✓'}</div><div className="status-stats"><span><b>{available?t.toFixed(1)+'°C':latest.temperature!=null?Number(latest.temperature).toFixed(1)+'°C':'--'}</b> Temperature</span><span><b>{available&&latest.humidity!=null?Math.round(latest.humidity)+'%':latest.humidity!=null?Math.round(latest.humidity)+'%':'--'}</b> Humidity</span><span><b>{available?(latest.fan?'ON':'OFF'):'--'}</b> Fan</span></div><div className="cabin-3d"><div className="cabin-glow"/><div className="cabin-roof"/><div className="cabin-window"/><div className="cabin-seat seat-left"/><div className="cabin-seat seat-right"/><div className="cabin-console"/><span className="hotspot h-pir">PIR<br/><b>{available?(latest.pir?'MOTION':'CLEAR'):'--'}</b></span><span className="hotspot h-ir">IR<br/><b>{available?(latest.ir?'OBJECT':'CLEAR'):'--'}</b></span><span className="hotspot h-gas">MQ-3<br/><b>{available?(gas?'ALERT':'OK'):'--'}</b></span></div></div>
 <div className="grid gauges"><Card title="Temperature" icon="🌡"><Gauge value={latest.temperature} max={50} unit="°C" label={high?'HIGH':'NORMAL'} available={available}/></Card><Card title="Humidity" icon="💧"><Gauge value={latest.humidity} max={100} unit="%" label="RELATIVE HUMIDITY" available={available}/></Card><Card title="MQ-3 Gas / Alcohol" icon="🧪"><Gauge value={latest.mq3} max={100} unit="DO" label={gas?'ALERT':'NORMAL'} available={available}/><small>Digital trigger • not calibrated ppm</small></Card><Card title="MQ-7 Carbon Monoxide" icon="☁"><Gauge value={latest.mq7} max={100} unit="ADC" label={co?'ALERT':'NO DATA'} available={available&&latest.mq7!=null}/><small>Requires ADS1115 analog stage</small></Card></div>
 <div className="grid lower"><Card title="Cabin Sensors" icon="◉" extra={available?'LIVE':'NO DATA'}><div className="rows"><div><span>👤 PIR Motion</span><b className={!available?'muted':latest.pir?'warn':'ok'}>{!available?'NO DATA':latest.pir?'MOTION':'CLEAR'}</b>{available&&<button onClick={()=>test('pir')}>Test</button>}</div><div><span>◈ IR Object Detection</span><b className={!available?'muted':latest.ir?'warn':'ok'}>{!available?'NO DATA':latest.ir?'OBJECT':'CLEAR'}</b>{available&&<button onClick={()=>test('ir')}>Test</button>}</div><div><span>🧪 MQ-3</span><b className={!available?'muted':gas?'bad':'ok'}>{!available?'NO DATA':gas?'ALERT':'NORMAL'}</b></div><div><span>☁ MQ-7</span><b className={!available?'muted':co?'bad':'ok'}>{!available?'NO DATA':co?'ALERT':latest.mq7==null?'NO DATA':'NORMAL'}</b></div></div></Card>
 <Card title="Actuators & Automation" icon="⚙"><div className="rows"><div><span>🔊 Buzzer Alert</span><b className={!available?'muted':latest.buzzer?'warn':'ok'}>{!available?'NO DATA':latest.buzzer?'ON':'OFF'}</b></div><div><span>🌀 12V Cooling Fan</span><b className={!available?'muted':latest.fan?'ok':'muted'}>{!available?'NO DATA':latest.fan?'ON':'OFF'}</b>{available&&<button onClick={()=>command('fan',!latest.fan)}>{latest.fan?'OFF':'ON'}</button>}</div><div><span>Automatic temperature fan</span><label className="switch"><input type="checkbox" checked={autoFan} onChange={e=>setAutoFan(e.target.checked)}/><i/></label></div><div className="threshold"><span>Fan threshold</span><input type="range" min="25" max="45" value={threshold} onChange={e=>setThreshold(+e.target.value)}/><b>{threshold}°C</b></div></div></Card></div>
 <div className="grid lower"><Card title="Cabin Safety Score" icon="◈"><div className="score"><div className="score-value">{score==null?'--':score}</div><div className="score-label">LIVE CONDITION INDEX</div></div></Card><Card title="Connection Health" icon="⌁"><div className="info"><div><span>ESP8266</span><b className={connected?'ok':'bad'}>{connected?'ONLINE':'OFFLINE'}</b></div><div><span>API latency</span><b>{apiMs==null?'--':apiMs+' ms'}</b></div><div><span>Heartbeat</span><b>{latest.lastDeviceUpdate?new Date(latest.lastDeviceUpdate).toLocaleTimeString():'--'}</b></div><div><span>Cloud endpoint</span><b>Render API</b></div></div></Card></div>
 <Card title="Sensor History" icon="▥" extra={connected?'LIVE':'PAUSED'}><div className="chart">{connected&&history.length?<ResponsiveContainer width="100%" height={270}><AreaChart data={history}><CartesianGrid strokeDasharray="3 3" opacity=".15"/><XAxis dataKey="t"/><YAxis/><Tooltip/><Area type="monotone" dataKey="temp" strokeWidth={2} stroke="currentColor" fill="none" name="Temperature °C"/><Line type="monotone" dataKey="hum" strokeWidth={2} strokeDasharray="5 5" stroke="currentColor" name="Humidity %"/></AreaChart></ResponsiveContainer>:<div className="chart-empty">Waiting for live ESP8266 readings…</div>}</div></Card>
 </>}
 {tab==='events'&&<><Card title="Alert History" icon="◷" extra={alerts.length+' events'}><div className="toolbar"><button onClick={clearAlerts}>Clear alerts</button></div><div className="alerts">{alerts.length?alerts.map((a,i)=><div className="alert" key={i}><span className={'alert-icon '+a.type.toLowerCase()}>{a.type==='NORMAL'?'✓':'!'}</span><div><b>{a.text}</b><small>{a.time}</small></div><em>{a.type}</em></div>):<div className="notice">No alerts recorded.</div>}</div></Card><Card title="Event Log" icon="▤"><div className="event-table">{events.length?events.map((e,i)=><div className="event-row" key={i}><span>{e.time}</span><b>{e.event}</b><span className={e.level==='CRITICAL'?'bad':e.level==='WARNING'?'warn':'ok'}>{e.value}</span></div>):<div className="notice">No test events yet.</div>}</div></Card></>}
 {tab==='tests'&&<><div className="notice"><strong>Hardware test mode:</strong> these controls write test states to the API. Real ESP8266 telemetry will overwrite them on its next heartbeat.</div><Card title="Sensor Tests" icon="🧪"><div className="toolbar"><button disabled={!available||testing} onClick={()=>test('pir')}>PIR</button><button disabled={!available||testing} onClick={()=>test('ir')}>IR</button><button disabled={!available||testing} onClick={()=>test('mq3')}>MQ-3</button><button disabled={!available||testing} onClick={()=>test('mq7')}>MQ-7</button><button disabled={!available||testing} onClick={()=>test('buzzer')}>Buzzer</button></div></Card><Card title="Actuator Tests" icon="⚙"><div className="toolbar"><button disabled={!available} onClick={()=>command('fan',true)}>Fan ON</button><button disabled={!available} onClick={()=>command('fan',false)}>Fan OFF</button></div></Card></>}
 <div className="grid bottom"><Card title="System Information" icon="ⓘ"><div className="info"><div><span>Device</span><b>NodeMCU V3 / ESP8266</b></div><div><span>Firmware</span><b>Smart Cabin Safety</b></div><div><span>Connection</span><b className={connected?'ok':'bad'}>{connected?'Wi-Fi / API':'Offline'}</b></div><div><span>Last heartbeat</span><b>{latest.lastDeviceUpdate?new Date(latest.lastDeviceUpdate).toLocaleTimeString():'--'}</b></div><div><span>Fan mode</span><b>{autoFan?'Automatic':'Manual'}</b></div><div><span>Gas sensing</span><b>MQ-3 digital / MQ-7 ADS1115 planned</b></div></div></Card><Card title="Safety Features" icon="✓"><div className="info"><div><span>Temperature protection</span><b>Enabled</b></div><div><span>Gas/CO alerting</span><b>Enabled</b></div><div><span>Motion detection</span><b>Enabled</b></div><div><span>Object detection</span><b>Enabled</b></div><div><span>Heartbeat monitoring</span><b>Enabled</b></div><div><span>Event logging</span><b>Enabled</b></div></div></Card></div>
 </main><footer>SMART CABIN SAFETY • ESP8266 IoT MONITORING PLATFORM</footer></div>}