import React,{useEffect,useState}from'react';
import{LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,AreaChart,Area}from'recharts';
const seed=[{t:'--:--',temp:31,hum:66}];
const Gauge=({value,max,unit,label})=>{const n=Number(value)||0,p=Math.min(100,Math.max(0,n/max*100));return <div className="gauge"><div className="ring" style={{'--p':p+'%'}}><div className="ring-inner"><b>{n}</b><span>{unit}</span></div></div><div className="gauge-label">{label}</div><div className="meter"><i style={{width:p+'%'}}/></div></div>};
const Card=({title,icon,children,extra=''})=><section className="card"><div className="card-head"><span>{icon} {title}</span><small>{extra}</small></div>{children}</section>;
const now=()=>new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'});
export default function App(){
 const[latest,setLatest]=useState({temperature:31,humidity:66,mq3:0,mq7:0,pir:false,ir:false,buzzer:false,fan:false});
 const[data,setData]=useState(seed),[connected,setConnected]=useState(false),[alerts,setAlerts]=useState([{time:now(),text:'Dashboard started — waiting for ESP8266',type:'NORMAL'}]);
 const[autoFan,setAutoFan]=useState(true),[threshold,setThreshold]=useState(35);
 const addAlert=(text,type='WARNING')=>setAlerts(a=>[{time:now(),text,type},...a].slice(0,12));
 const poll=async()=>{try{const r=await fetch('/api/status',{cache:'no-store'});if(!r.ok)throw 0;const s=await r.json();const x={...s,temperature:Number(s.temperature)||0,humidity:Number(s.humidity)||0,mq3:Number(s.mq3)||0,mq7:Number(s.mq7)||0,pir:!!s.pir,ir:!!s.ir,buzzer:!!s.buzzer,fan:!!s.fan};setLatest(x);setConnected(true);setData(d=>[...d.slice(-19),{t:now(),temp:x.temperature,hum:x.humidity}]);}catch{setConnected(false)}};
 useEffect(()=>{poll();const id=setInterval(poll,2000);return()=>clearInterval(id)},[]);
 const high=latest.temperature>=threshold,gas=latest.mq3>=50,co=latest.mq7>=50,critical=gas||co,warning=high||latest.pir||latest.ir,status=critical?'CRITICAL':warning?'WARNING':'SAFE';
 const test=async(field,label)=>{try{await fetch('/api/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({[field]:!latest[field]})});await poll();addAlert(label)}catch{addAlert('API unavailable','CRITICAL')}};
 const fan=async value=>{await fetch('/api/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fan:value})});poll()};
 useEffect(()=>{if(latest.pir)addAlert('PIR motion detected')},[latest.pir]);
 useEffect(()=>{if(latest.ir)addAlert('IR object detected')},[latest.ir]);
 useEffect(()=>{if(gas)addAlert('MQ-3 gas/alcohol level high','CRITICAL')},[gas]);
 useEffect(()=>{if(co)addAlert('MQ-7 CO level high','CRITICAL')},[co]);
 return <div className="app"><header><div className="brand"><span className="shield">⬡</span><div><h1>SMART CABIN SAFETY</h1><p>Vehicle safety monitoring & automation</p></div></div><div className="connection"><span className={'dot '+(connected?'online':'')}/><div><b>{connected?'ESP8266 ONLINE':'ESP8266 OFFLINE'}</b><small>{connected?'Live API • 2s updates':'Waiting for device data'}</small></div></div></header>
 <main><div className="status card"><div><span className="eyebrow">LIVE SYSTEM STATUS</span><h2 className={status.toLowerCase()}>{status}</h2><p>{critical?'Immediate attention required':warning?'Safety condition detected':'All monitored conditions are normal'}</p></div><div className="status-orb">{critical?'⚠':warning?'!':'✓'}</div><div className="status-stats"><span><b>{latest.temperature.toFixed(1)}°C</b> Temperature</span><span><b>{Math.round(latest.humidity)}%</b> Humidity</span><span><b>{latest.fan?'ON':'OFF'}</b> Fan</span></div></div>
 <div className="grid gauges"><Card title="Temperature" icon="🌡"><Gauge value={latest.temperature.toFixed(1)} max={50} unit="°C" label={high?'HIGH':'NORMAL'}/></Card><Card title="Humidity" icon="💧"><Gauge value={Math.round(latest.humidity)} max={100} unit="%" label="RELATIVE HUMIDITY"/></Card><Card title="MQ-3 Gas / Alcohol" icon="🧪"><Gauge value={latest.mq3} max={100} unit="%" label={gas?'DETECTED':'NORMAL'}/><button className={gas?'danger':''} onClick={()=>test('mq3',gas?'MQ-3 test cleared':'MQ-3 test alert')}>{gas?'Clear test':'Test alert'}</button></Card><Card title="MQ-7 Carbon Monoxide" icon="☁"><Gauge value={latest.mq7} max={100} unit="%" label={co?'DETECTED':'NORMAL'}/><button className={co?'danger':''} onClick={()=>test('mq7',co?'MQ-7 test cleared':'MQ-7 test alert')}>{co?'Clear test':'Test alert'}</button></Card></div>
 <div className="grid lower"><Card title="Cabin Sensors" icon="◉" extra="LIVE"><div className="rows"><div><span>👤 PIR Motion</span><b className={latest.pir?'warn':'ok'}>{latest.pir?'MOTION':'CLEAR'}</b><button onClick={()=>test('pir','PIR test toggled')}>Test</button></div><div><span>◈ IR Object Detection</span><b className={latest.ir?'warn':'ok'}>{latest.ir?'OBJECT':'CLEAR'}</b><button onClick={()=>test('ir','IR test toggled')}>Test</button></div><div><span>🧪 MQ-3</span><b className={gas?'bad':'ok'}>{gas?'ALERT':'NORMAL'}</b></div><div><span>☁ MQ-7</span><b className={co?'bad':'ok'}>{co?'ALERT':'NORMAL'}</b></div></div></Card>
 <Card title="Actuators & Automation" icon="⚙"><div className="rows"><div><span>🔊 Buzzer Alert</span><b className={latest.buzzer?'warn':'ok'}>{latest.buzzer?'ON':'OFF'}</b></div><div><span>🌀 12V Cooling Fan</span><b className={latest.fan?'ok':'muted'}>{latest.fan?'ON':'OFF'}</b><button onClick={()=>fan(!latest.fan)}>{latest.fan?'Turn off':'Turn on'}</button></div><div><span>Automatic temperature fan</span><label className="switch"><input type="checkbox" checked={autoFan} onChange={e=>setAutoFan(e.target.checked)}/><i/></label></div><div className="threshold"><span>Fan threshold</span><input type="range" min="25" max="45" value={threshold} onChange={e=>setThreshold(+e.target.value)}/><b>{threshold}°C</b></div></div></Card></div>
 <Card title="Sensor History" icon="▥" extra="LIVE"><div className="chart"><ResponsiveContainer width="100%" height={270}><AreaChart data={data}><CartesianGrid strokeDasharray="3 3" opacity=".15"/><XAxis dataKey="t"/><YAxis/><Tooltip/><Area type="monotone" dataKey="temp" strokeWidth={2} stroke="currentColor" fill="none" name="Temperature °C"/><Line type="monotone" dataKey="hum" strokeWidth={2} strokeDasharray="5 5" stroke="currentColor" name="Humidity %"/></AreaChart></ResponsiveContainer></div></Card>
 <div className="grid bottom"><Card title="Alert History" icon="◷"><div className="alerts">{alerts.map((a,i)=><div className="alert" key={i}><span className={'alert-icon '+a.type.toLowerCase()}>{a.type==='NORMAL'?'✓':'!'}</span><div><b>{a.text}</b><small>{a.time}</small></div><em>{a.type}</em></div>)}</div></Card><Card title="System Information" icon="ⓘ"><div className="info"><div><span>Device</span><b>NodeMCU V3 / ESP8266</b></div><div><span>Connection</span><b className={connected?'ok':'bad'}>{connected?'Wi-Fi / API':'Offline'}</b></div><div><span>Fan logic</span><b>{autoFan?'Automatic':'Manual'}</b></div><div><span>Gas sensors</span><b>MQ-3 + MQ-7</b></div><div><span>Data source</span><b>{connected?'ESP8266 API':'Waiting for ESP8266'}</b></div></div></Card></div></main><footer>SMART CABIN SAFETY • ESP8266 IoT Monitoring Platform</footer></div>}
